name: 打包 vue-pc-chat (Windows 版本)

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 使用 Node.js 14.18.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.18.x
          cache: 'npm'

      - run: npm install node-gyp@8.3.0
      
      # 更新 package-lock.json 文件
      - run: npm install --package-lock-only
      
      # 提交更新后的 package-lock.json 文件（可选）
      - name: 检查是否有文件变更
        id: check-changes
        run: |
          if (git diff --quiet) {
            echo "NO_CHANGES=true" >> $env:GITHUB_ENV
          } else {
            echo "NO_CHANGES=false" >> $env:GITHUB_ENV
          }
          
      - name: 提交更新后的 package-lock.json
        if: env.NO_CHANGES == 'false'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package-lock.json
          git commit -m "自动更新 package-lock.json"
          git push
          
      - run: npm ci
      - run: npm run cross-package-win
      - run: npm run cross-package-win32

      - name: 上传 Windows 打包产物
        uses: actions/upload-artifact@v4
        with:
          name: vue-pc-chat-windows
          path: |
            dist_electron/*.exe
          retention-days: 30
