name: 打包 vue-pc-chat

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest  # 更改运行环境为 Windows

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.18.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.18.x
      - run: npm install node-gyp@8.3.0
      - run: npm ci

      # 保留 Windows 打包步骤，移除 macOS 和 Linux 相关步骤
      - run: npm run cross-package-win
      - run: npm run cross-package-win32

      # 仅上传 Windows 安装包
      - uses: actions/upload-artifact@v3
        with:
          path: |
            dist_electron/*.exe